[project]
name = "trend-linkedin-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=1.16.1",
    "langsmith[openai-agents]>=0.3.42",
    "openai-agents>=0.0.15",
    "python-dotenv>=1.1.0",
]
